// backend/src/utils/knowledgeBase.js

// Make sure you have pasted the full text for each document inside the backticks ``.
const documents = {
    XEROX_SAVIOR: `Like lion taming, running an insurance company requires that you respect the particular animal you are working with: both have some hair on them - and both bite. There are definite benefits for those who take the time to deeply understand the nature of the beast. If you are not paying attention, you’ll probably get eaten alive. 
  This is especially true if you just bought a large, complex insurance company. Here’s an excerpt from the 1983 Xerox annual report: “The acquisition of C&F, a leading property and liability insurance company, represents a major change in the overall structure of Xerox, as well as a great opportunity. We believe C&F will broaden the base of our business, ensure greater stability in our performance, and enhance our growth potential. 
  Crum & Forster is a premier company. It has what many consider the best management team in its industry and has a reputation for high quality underwriting and service. Therefore, the acquisition of C&F will divert neither capital nor day-to-day attention from our basic business.” 
  Bobby Russell had reason to be enthusiastic: “Xerox is a top quality company and will provide us with a structure within which we can pursue exciting new opportunities.” Furthermore, he was happy that C&F would maintain its independence: “Xerox is not in the insurance business and never has been. So it’s not like putting two insurance organizations together, which always brings on a substantial amount of duplication. C&F has the total insurance ball, and our job is to keep doing what we’ve been doing — only better and more of it.” 
  Xerox CEO David Kearns seemed equally pleased, noting that “the C&F purchase would put Xerox in another growth business because financial services is one of the few businesses with a growth potential as exciting as our own information industry.” While P&C insurance can technically be lumper in with other financial services, industry insiders in 1983 would not have been thinking of insurance as a growth business — and certainly not as exciting as information technology, which was on the cusp of exponential growth. 
  But these two opening statements highlight the asymmetric nature of any insurance company acquisition. Russell was happy to have dodged a bullet: he cashed out and looked to be taking a valedictory lap. Kearns was blandly looking forward to some profitable growth — without realizing he had signed up for an unbounded liability hole that would put a drag on Xerox resources for decades. 
  In tech circles, Xerox is famous for squandering an opportunity to change the world. The story is that Xerox home office types invited Apple’s Steve Jobs for a visit to its Palo Alto Research Center (PARC) to check out what they were developing. The horrified PARC researchers were directed to show Jobs all the amazing technology they had developed in the mid-1970s — essentially everything necessary for modern personal computers, including graphical user interface, WYSIWYG display, mouse, keyboard, laser printing, Ethernet connections and a prototype personal desktop computer. 
  According to Steve Jobs, “They had no idea what they had.” 
  Computerworld summed it up in a November 6, 2000, article titled “The Xerox Tragedy”: 
  “The fate of Xerox can be traced to 1983, when conflicts between its computer-oriented innovators and xerography-focused sales force were settled by dooming the inventions from the company’s Palo Alto Research Center to being technological marvels without competent marketing to sell them. Shortly thereafter, Xerox management crippled itself from participating in the information races altogether by taking much of its cash and investing in ‘safer’ business lines such as insurance.” 
  Other stories from that era have titles such as “Fumbling the Future” and “Xerox: The Downfall,” as the one-time glamor stock plunged from a high of $149 a share in 1972 to $37 in late 1982. Analysts soon questioned the wisdom of the C&F acquisition, noting how diversification into the depressed insurance industry could not deliver the growth Xerox investors had been promised. 
  Before mutual funds allowed everyone to diversify their investments, corporations tried to diversify on behalf of their shareholders as an alternative to paying dividends. While the rise of the mutual fund industry showed that investor demand for diversification existed, the lack of expertise and an inability to execute successfully at many conglomerates resulted in quite a few “deworsifications.” The forays outside of their core competencies ended up being more likely to destroy shareholder value than create new avenues of growth. 
  As part of this conglomeration trend, many industrial companies were diversifying into financial services, including Teledyne, ITT, General Electric and Ford, among others. For some of these companies, including Xerox, success with their equipment leasing business was the first taste of what “financial services” could do to boost earnings. 
  Of course, along the spectrum of financial services, providing financing options for your own products is a long way from underwriting long-tail casualty insurance. 
  The honeymoon was short. Xerox put on a good face in the early going. Echoing Xerox’s issues with Japanese price competition in their core copier business, they soon blamed “the market” and competitor insurance companies involved in cash-flow underwriting. 
  In the 1984 Xerox annual report, David Kearns noted that total income from continuing operations was “significantly impacted by a sharp drop in the results of the Company’s financial services businesses … due entirely to the results of C&F.” As Kearns explains, C&F had “a disappointing year due to the industry-wide problem caused by several years of grossly inadequate price levels” and therefore, Xerox was forced to “take decisive action to address problem areas at C&F.” The “decisive action” involved rate increases, tightened underwriting controls, reduced expenses and further automation of its recordkeeping processes. 
  Anyone with a background in insurance is going to read that last paragraph and shake their head. Those don’t sound like decisive actions! 
  Unsurprisingly, the 1985 annual report was more stern: “We restructured operations at C&F to improve profitability.” This time Xerox took more decisive action, including reserve strengthening at L.W. Biegler (resulting in an after-tax charge of $164 million) and replenishing capital at C&F by $200 million. Then they put in place a new management team and strengthened the controls around the operation. 
  Even if you understood the risks involved, the early 1980s were a tough time to buy an insurance company balance sheet. Xerox was focused on income and growth — and thus might have overlooked the risks lurking in the balance sheet. Exposures like asbestos and environmental clean-ups that were never considered when underwriting casualty and package business started to produce claims. Inflation and increased litigation cut across all lines of business — retroactive to C&F’s first forays into casualty business — and made pricing policies and reserving for claim liabilities challenging. 
  All of these forces were starting toshow up at this time, precipitating the liability crisis that made the cover of Time magazine in March 1986. It would take the industry decades to fully wring these issues out of the system. Quite a few insurance companies were technically insolvent — and C&F was one of them. 
  From personal experience, turning an insurance company around is no picnic. Put yourself in the shoes of that C&F team. Claims for business that you wrote years ago are ballooning. This calls into question the capabilities of your underwriting team: Did they understand what they were signing you up for? It would also call into question your pricing actuaries’ ability to peer into the future: clearly you did not charge enough for the exposure. 
  Your claims professionals are seeing new types of claims — in fact, whole new categories of claims — as well as new levels of complexity in the resolution process and unprecedented settlement values on those claims. 
  Your actuarial process did not work at all — you thought your reserving actuaries were wildly conservative — but even they were wrong on the low side. Reinsurer partners who you relied on to cover their agreed-upon part of these claims are unwilling or unable to pay, as they are wrestling with the same problems you are having.`,
    VIKING_KKR: `Viking Insurance of Wisconsin (1992 NWP of $200 million), a nonstandard personal automobile insurer, not affected by restructuring. 
  From a financial engineering perspective, Xerox had done a masterful job of keeping C&F from requiring capital infusions (with the notable exception of a $200-million capital contribution in 1985, when L.W. Biegler hit the wall). To get the reorganization to work, they needed to put money in — but they now had some hope of getting the companies sold and getting that money back. Talegen had a net loss of $779 million in 1992 and required a capital infusion of $200 million. In 1993, Talegen needed another support package of $535 million. 
  In 1994, Jay and his Talegen team came up with the idea for Ridge Re: a reinsurance company to backstop the reserves (up to 85% of $1.25 billion) of the individual companies. It was this final piece that really increased the curb appeal of the balance sheets for sale. 
  The plan worked. In 1995, Xerox sold Constitution Re to Exor American for $421 million. Viking was sold to Guaranty National for $103 million. Then came the big news that Kohlberg Kravis Roberts (KKR) had agreed to sponsor a management buy-out (MBO) of the remaining companies for $2.7 billion. After all the work to split C&F into bite-sized nuggets, the company was going to be sold as a whole. 
  I was a junior member of the “M” in the MBO. Jay came to Chicago to explain the deal. He was going to give each of the MBO participants some money to put into the deal and encouraged us to add in whatever else we had. He gave each of us a spreadsheet model to show us how it worked. I looked at the spreadsheet — and then went back into the boardroom where he was waiting. 
  Jay was standing on the table blowing smoke into a vent. (Smoking had recently been banned in Chicago office buildings.) He asked what I thought; I thanked him for the money and told him I was happy to roll it into the deal. He asked about other money; I told him that I was 29 and didn’t have any other money. He asked me where the other people were; I said they probably had more scenarios to run. He chortled. 
  At the conclusion of the KKR deal, Xerox’s foray into insurance would just about break even, which is actually better than I expected when I started researching the topic. Of course, in 1983, Xerox could have bought 30-year Treasury bonds paying 11%. Or they could have pulled a Forrest Gump and bought Apple stock. (Actually, in January 1983, Apple’s market cap was $1.3 billion — less than what Xerox paid for C&F — so they could have bought the whole thing!) 
  Reading the Xerox 1995 annual report would have led you to believe the KKR deal was done. But it did not work out. KKR wanted to renegotiate the price after a re-look at the reserves for California construction defect claims (which were starting to be an issue industry-wide) — and Xerox did not go for it.`,
    FGIC_ERC: `The plan was that FGIC would absorb the part of Coregis that catered to public entities, so they could cross-sell municipal bond insurance, with everything else going to ERC (since they had already passed on the deal, they were not that excited to get the “all other” bucket). Owing to my winning personality, I was given a choice of staying with FGIC in Chicago or joining ERC in suburban Kansas City. I decided ERC was the better option. 
  It is worth mentioning that a closer examination of GE’s published numbers at this time showed that the lion’s share of their profit came from GE Capital, and the lion’s share of GE Capital’s profits came from ERC. Because they were seen as such a moneymaker, ERC had — to that point — fended off most of the GE approach (in retrospect, including some basic enterprise risk management). 
  Fortunately, I had accelerated taking my MBA classes — but even more fortunately, I still had a few months left. This gave me enough time to realize that there was something off with ERC: they were nice people, but there was no way that their business underpinned GE’s profit machine. I never made it to Kansas City. 
  GE eventually put people from the industrial side in charge of ERC and Coregis. ERC blew up a few years later (asbestos, environmental and other long-term casualty liabilities) and was sold for parts to Swiss Re, although I think GE is still paying off long-term care insurance liabilities from that time. FGIC blew up during the 2008 credit meltdown. 
  There are not a lot of examples of stellar insurance company acquisitions. Consequently, some of the other C&F spin-offs also went from the frying pan right into the fire. For example, Constitution Reinsurance was sold by Exor to Gerling Global Re in 1998, and then Gerling Global Re went into run-off in 2002. In 1997, Industrial Indemnity was sold for $365 million to Fremont Insurance Company, which was insolvent by 2003. 
  Viking and Guaranty National were absorbed into Sentry Insurance in 2005. The Resolution Group executed a $150-million management buy-out and was later sold to Fairfax, while Westchester was sold to Ace (now part of Chubb) for $338 million — and is still going strong. 
  Let’s see, who do we have left? Oh yeah, Crum & Forster. 
  It is probably not a coincidence that C&F was the last in line. While C&F was the largest of the business units, it was the least specialized — and the company had neglected its retail-produced standard lines middle market business while chasing after the more exciting specialty businesses that had all now been sold or run-off. C&F was still a fixer-upper. Still, Jay was very motivated to get Xerox out of the insurance business once and for all, so he started preparing for an IPO. The S-1 was filed and ready — and then, in the spring of 1998, Fairfax Financial showed up and offered $680 million for C&F. 
  And a new era began.`,
};

// This function simulates the "Retrieval" part of RAG
const retrieveContext = (query) => {
    const lowerCaseQuery = query.toLowerCase();

    // For debugging, let's see what query we're getting
    console.log(`[Knowledge Base] Searching for context with query: "${lowerCaseQuery}"`);

    // Added more keywords to make matching more reliable
    if (lowerCaseQuery.includes('xerox') || lowerCaseQuery.includes('savior') || lowerCaseQuery.includes('russell') || lowerCaseQuery.includes('crum')) {
        console.log('[Knowledge Base] Found match: XEROX_SAVIOR');
        return documents.XEROX_SAVIOR;
    }
    if (lowerCaseQuery.includes('viking') || lowerCaseQuery.includes('kkr') || lowerCaseQuery.includes('ridge re') || lowerCaseQuery.includes('talegen')) {
        console.log('[Knowledge Base] Found match: VIKING_KKR');
        return documents.VIKING_KKR;
    }
    if (lowerCaseQuery.includes('fgic') || lowerCaseQuery.includes('erc') || lowerCaseQuery.includes('ge capital') || lowerCaseQuery.includes('coregis')) {
        console.log('[Knowledge Base] Found match: FGIC_ERC');
        return documents.FGIC_ERC;
    }

    // If no specific keywords match, we'll return a default document to avoid an error.
    console.log('[Knowledge Base] No specific match found, returning default document.');
    return documents.XEROX_SAVIOR;
};

module.exports = { retrieveContext };